# Generated by Django 3.1.6 on 2021-02-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapiauthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRecord',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CityRecord',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('pincode', models.CharField(default=None, max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tokenapiauthapp.countryrecord')),
            ],
        ),
    ]
